import { z } from 'zod';

export const tenantBusinessProfileSchema = z.object({
  tenant_id: z.string().uuid().optional(),
  legal_name: z.string().optional(),
  trade_name: z.string().min(1, 'Nome fantasia é obrigatório'),
  owner_name: z.string().optional(),
  tagline: z.string().optional(),
  description: z.string().optional(),
  founded_year: z.number().int().min(1900).max(2030).optional(),
  logo_url: z.string().url().optional().or(z.literal('')),
  business_phone: z.string().min(1, 'Telefone comercial é obrigatório'),
  whatsapp_number: z.string().optional(),
  business_email: z.string().email().optional().or(z.literal('')),
  website_url: z.string().url().optional().or(z.literal('')),
  instagram_handle: z.string().optional(),
  google_maps_url: z.string().url().optional().or(z.literal('')),
  address_street: z.string().optional(),
  address_number: z.string().optional(),
  address_complement: z.string().optional(),
  address_neighborhood: z.string().optional(),
  city: z.string().optional(),
  state: z.string().optional(),
  zip_code: z.string().optional(),
  landmark: z.string().optional(),
  business_style: z.enum(['classica', 'moderna', 'premium', 'urbana', 'vintage', 'familiar']).optional(),
  target_audience: z.string().optional(),
  price_positioning: z.enum(['popular', 'intermediario', 'premium', 'luxo']).optional(),
  differentiators: z.string().optional(),
  dress_code: z.string().optional(),
  amenities: z.array(z.string()).optional(),
  opening_hours: z.record(z.string(), z.unknown()).default({}),
  holiday_dates: z.array(z.string()).optional(),
  special_hours: z.record(z.string(), z.unknown()).optional(),
  payment_methods: z.array(z.string()).optional(),
  accepts_walk_in: z.boolean().optional(),
  requires_deposit: z.boolean().optional(),
  deposit_percentage: z.number().int().min(0).max(100).optional(),
  updated_at: z.string().optional(),
});

export type TenantBusinessProfile = z.infer<typeof tenantBusinessProfileSchema>;